"""URLs excluidas manualmente en la calibracion inicial del filtro de dominio.

Generado 2026-09-22 a partir de la revision humana de 58 candidatos de
ColombiaCheck con coincidencia incidental de una sola palabra clave (ver
02_corpus/criterios_seleccion_fuentes.md, seccion de calibracion). Estas 53
URLs se determinaron ruido politico/no financiero tras revision manual, no por
una regla automatica -- ver la discusion de por que se descarto automatizarlo.
"""

EXCLUSIONES_MANUALES: set[str] = {
    'https://colombiacheck.com/chequeos/estas-fotografias-no-corresponden-con-el-conflicto-actual-entre-iran-e-israel',
    'https://colombiacheck.com/chequeos/el-congreso-de-eu-acaba-de-frenar-el-poder-de-trump-falso',
    'https://colombiacheck.com/chequeos/petro-difundio-foto-manipulada-con-ia-de-narcosubmarino-teledirigido-confiscado-por-la',
    'https://colombiacheck.com/chequeos/pastrana-y-santos-ya-no-hacen-parte-de-la-junta-directiva-de-thomas-greg-sons',
    'https://colombiacheck.com/chequeos/estas-fotos-no-corresponden-un-tsunami-en-julio-de-2025',
    'https://colombiacheck.com/chequeos/petro-trato-de-descalificar-foto-verdadera-de-marcha-contra-la-condena-de-alvaro-uribe',
    'https://colombiacheck.com/chequeos/petro-amana-avances-en-nuevos-cupos-universitarios-y-castillo-se-precipita-declarar',
    'https://colombiacheck.com/chequeos/mensaje-contra-miguel-uribe-tras-su-muerte-recicla-montaje-que-le-atribuye-frase-sobre-eps',
    'https://colombiacheck.com/chequeos/montaje-con-ia-simula-la-presidenta-de-mexico-pidiendo-la-extradicion-de-alvaro-uribe',
    'https://colombiacheck.com/chequeos/juicios-al-duelo-de-claudia-tarazona-y-sus-hijas-por-miguel-uribe-sacan-de-contexto-fotos',
    'https://colombiacheck.com/chequeos/quienes-piden-declarar-incapacidad-mental-de-petro-son-politicos-no-la-asociacion-de',
    'https://colombiacheck.com/chequeos/presuntas-confesiones-de-el-pollo-carvajal-provienen-de-una-entrevista-que-nunca-sucedio',
    'https://colombiacheck.com/chequeos/video-de-pesqueros-chinos-circula-como-si-fuera-la-flotilla-global-sumud-rumbo-gaza',
    'https://colombiacheck.com/chequeos/busto-del-expresidente-nieto-en-alocucion-de-petro-fue-reemplazado-por-el-de-stalin-con-ia',
    'https://colombiacheck.com/chequeos/ee-uu-si-es-el-mas-consumidor-de-cocaina-y-colombia-el-mas-incautador-pero-con-produccion',
    'https://colombiacheck.com/chequeos/kirk-musk-y-metallica-carnada-para-clics-con-mentira-sobre-manutencion-de-los-hijos-del',
    'https://colombiacheck.com/chequeos/montaje-acomoda-audio-de-petro-para-que-parezca-decir-que-va-expropiar-al-estilo-de-chavez',
    'https://colombiacheck.com/chequeos/aunque-petro-hablo-de-sacar-trump-no-dijo-que-deba-irse-por-las-buenas-o-por-las-malas',
    'https://colombiacheck.com/chequeos/video-viejo-de-logo-chino-bajo-la-bandera-de-ee-uu-en-un-puerto-circula-por-guerra',
    'https://colombiacheck.com/chequeos/pelea-entre-gustavo-petro-y-dilian-francisca-toro-revive-falso-audio-atribuido-w-radio',
    'https://colombiacheck.com/chequeos/sofia-petro-no-advirtio-de-un-estallido-social-si-ivan-cepeda-no-gana-en-2026',
    'https://colombiacheck.com/chequeos/ley-que-obligaria-candidatos-asistir-debates-todavia-no-se-ha-aprobado-apenas-esta-en',
    'https://colombiacheck.com/chequeos/usan-imagen-de-supuesto-libro-de-petro-generada-por-ia-para-atacarlo-con-mensajes',
    'https://colombiacheck.com/chequeos/con-datos-imprecisos-repiten-la-mentira-de-que-petro-no-le-ha-hecho-reformas-la',
    'https://colombiacheck.com/chequeos/el-gobierno-esta-dando-un-nuevo-bono-de-hasta-200000-segun-el-estrato',
    'https://colombiacheck.com/chequeos/ivan-mordisco-no-anuncio-que-colaborara-con-la-fiscalia-para-entregar-pruebas-sobre',
    'https://colombiacheck.com/chequeos/petro-no-ordeno-las-aerolineas-del-mundo-restablecer-sus-vuelos-hacia-venezuela',
    'https://colombiacheck.com/chequeos/calarca-no-agradece-petro-o-su-gobierno-en-chats-revelados-por-noticias-caracol',
    'https://colombiacheck.com/chequeos/foto-vieja-circula-como-si-fuera-un-arresto-de-ice-venezolanos-que-celebraban-la-captura',
    'https://colombiacheck.com/chequeos/sueldos-de-500-nuevos-cargos-en-mintrabajo-estan-muy-lejos-de-los-45-millones-mensuales',
    'https://colombiacheck.com/chequeos/montaje-pone-cepeda-en-la-liberacion-de-santrich-equivocada-fue-la-fiscalia-no-la-picota',
    'https://colombiacheck.com/chequeos/valla-contra-la-corte-constitucional-que-invita-votar-por-el-pacto-historico-es-un-montaje',
    'https://colombiacheck.com/chequeos/video-de-hombres-con-cuchillos-en-las-calles-de-bogota-no-muestra-colectivos-petristas-ni',
    'https://colombiacheck.com/chequeos/esta-foto-de-reses-muertas-por-las-inundaciones-en-cordoba-fue-generada-con-ia',
    'https://colombiacheck.com/chequeos/ia-creo-este-video-del-regano-de-una-mujer-therians-en-un-centro-comercial-de-colombia',
    'https://colombiacheck.com/chequeos/peticion-de-investigar-cepeda-por-farc-politica-usa-montaje-que-lo-junta-con-ivan-marquez',
    'https://colombiacheck.com/chequeos/ia-disfraza-al-exsenador-mario-laserna-abuelo-de-paloma-valencia-como-guerrillero-del-m-19',
    'https://colombiacheck.com/chequeos/engano-sobre-interesados-en-traslado-de-hipopotamos-invasores-alienta-indignacion-por',
    'https://colombiacheck.com/chequeos/senalamientos-infundados-uribe-por-atentados-sacan-de-contexto-frase-sobre-bombardear',
    'https://colombiacheck.com/chequeos/falsa-relacion-madre-hija-entre-juliana-guerrero-y-jefa-del-eln-se-basa-en-su-alias',
    'https://colombiacheck.com/chequeos/pagina-huilense-de-facebook-preve-triunfo-de-valencia-con-base-en-datos-de-portal-de',
    'https://colombiacheck.com/chequeos/video-recorta-discurso-de-petro-para-insinuar-que-gastara-toda-la-plata-antes-del-cambio',
    'https://colombiacheck.com/chequeos/petro-basa-narrativa-de-fraude-por-desfase-en-el-censo-electoral-en-mentiras-sobre',
    'https://colombiacheck.com/chequeos/imagen-falsa-atribuye-abelardo-de-la-espriella-frase-sobre-acabar-el-sisben',
    'https://colombiacheck.com/chequeos/de-la-espriella-no-propuso-congelar-el-salario-minimo-por-cuatro-anos-como-afirma-un',
    'https://colombiacheck.com/chequeos/pobreza-bajo-y-crecio-la-clase-media-pero-petro-infla-cifra-de-personas-que-salieron-de-la',
    'https://colombiacheck.com/chequeos/la-corte-suprema-no-ha-ratificado-que-el-gobierno-petro-este-al-dia-con-las-eps',
    'https://colombiacheck.com/chequeos/video-que-asegura-que-se-anula-la-eleccion-de-abelardo-de-la-espriella-es-clickbait-y',
    'https://colombiacheck.com/chequeos/es-falso-que-abelardo-de-la-espriella-no-pueda-posesionarse-el-7-de-agosto',
    'https://colombiacheck.com/chequeos/trino-hace-comparacion-cuestionable-sobre-la-magnitud-de-los-terremotos-en-colombia-y',
    'https://colombiacheck.com/chequeos/petro-viajo-mexico-para-dar-una-conferencia-en-la-unam-no-para-asumir-como-asesor',
    'https://colombiacheck.com/chequeos/supuesto-trino-del-bolillo-gomez-en-apoyo-petro-es-un-montaje',
    'https://colombiacheck.com/chequeos/samuel-adrian-fue-detenido-por-desacato-judicial-no-por-exponer-red-de-maltrato-infantil',
}
